// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD65iGcDtE9Xit7NzSG7Q1Gkv3gfcyQbYE',
    appId: '1:955602734381:web:16d0b9c8837ed51faa97a4',
    messagingSenderId: '955602734381',
    projectId: 'expolog-calc',
    authDomain: 'expolog-calc.firebaseapp.com',
    storageBucket: 'expolog-calc.appspot.com',
    measurementId: 'G-NJV41727Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkpw2YG_2wUBfKkSkkgKLCBLjWH1hK5X4',
    appId: '1:955602734381:android:f59c5f76781b5f18aa97a4',
    messagingSenderId: '955602734381',
    projectId: 'expolog-calc',
    storageBucket: 'expolog-calc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mzWAneiu5h3FLYVf5a3FI0DM4qio66I',
    appId: '1:955602734381:ios:d0b06a4422bc009baa97a4',
    messagingSenderId: '955602734381',
    projectId: 'expolog-calc',
    storageBucket: 'expolog-calc.appspot.com',
    iosClientId: '955602734381-thqomf07b04p13hktihp9pqc08kjgjqo.apps.googleusercontent.com',
    iosBundleId: 'com.nostracode.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5mzWAneiu5h3FLYVf5a3FI0DM4qio66I',
    appId: '1:955602734381:ios:55c6ec0d28a10673aa97a4',
    messagingSenderId: '955602734381',
    projectId: 'expolog-calc',
    storageBucket: 'expolog-calc.appspot.com',
    iosClientId: '955602734381-t0vao47bicne7kr4c85adathnibbqqs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCalculator.RunnerTests',
  );
}
