// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp48yT9A5QkBthM2OOkiSVfwEtodsG-kA',
    appId: '1:615709146253:web:a2dc9459d58ea30f6ef6c4',
    messagingSenderId: '615709146253',
    projectId: 'kalkulator-uas',
    authDomain: 'kalkulator-uas.firebaseapp.com',
    storageBucket: 'kalkulator-uas.appspot.com',
    measurementId: 'G-W3DBNJMTZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ10dHdmFOyQGA6mKhQb9-yfmambZkUJI',
    appId: '1:615709146253:android:599b30b9bcad05aa6ef6c4',
    messagingSenderId: '615709146253',
    projectId: 'kalkulator-uas',
    storageBucket: 'kalkulator-uas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0rAVShRHNJ0rE78eiagp-wIMMclUf60',
    appId: '1:615709146253:ios:067c597fe3c863fc6ef6c4',
    messagingSenderId: '615709146253',
    projectId: 'kalkulator-uas',
    storageBucket: 'kalkulator-uas.appspot.com',
    iosClientId: '615709146253-dariklct96h32cchfjre0dslnhdflm3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalkulatorUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK0rAVShRHNJ0rE78eiagp-wIMMclUf60',
    appId: '1:615709146253:ios:067c597fe3c863fc6ef6c4',
    messagingSenderId: '615709146253',
    projectId: 'kalkulator-uas',
    storageBucket: 'kalkulator-uas.appspot.com',
    iosClientId: '615709146253-dariklct96h32cchfjre0dslnhdflm3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalkulatorUas',
  );
}
